#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source ../settings/scripts/_ynh_detect_arch
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

db_name="$app"
db_user="$app"

domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path)
final_path=$(ynh_app_setting_get "$app" final_path)
salt=$(ynh_app_setting_get "$app" salt)
db_pwd=$(ynh_app_setting_get "$app" psqlpwd)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

architecture=$(ynh_detect_arch)
# Check machine architecture (in particular, we don't support ARM and 32bit machines)
if [ $architecture == "i386" ]
then
	ynh_die --message="Sorry, because of nodejs framework, this app can't be installed on i386 (32 bits) machine."
fi

ynh_webpath_available "$domain" "$path_url" \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d "$final_path" \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore_file "$final_path"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

# Create the dedicated user (if not existing)
ynh_system_user_create "$app"

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown -R "$app": "$final_path"
chmod 600 "$final_path/config.ini"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

# Define and install dependencies
ynh_install_app_dependencies $pkg_dependencies

#=================================================
# INSTALL NODEJS
#=================================================

ynh_install_nodejs 12

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================

ynh_psql_test_if_first_run
ynh_print_OFF
ynh_psql_setup_db "$db_user" "$db_name" "$db_pwd"
ynh_print_ON
ynh_psql_execute_file_as_root --file="${YNH_CWD}/dump.sql" --database="$db_name"

#=================================================
# RESTORE SYSTEMD
#=================================================

ynh_restore_file "/etc/systemd/system/$app.service"
systemctl enable "$app".service

#=================================================
# START KRESUS
#=================================================

systemctl start "$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================

systemctl reload nginx
