#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path=systemd

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -d "/home/ynh$app" ]; then
	mv "/home/ynh$app/data" "$install_dir/data"
	ynh_safe_rm "/home/ynh$app"
fi

# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=salt --value=$(ynh_string_random --length=40)
if [ -z "${salt:-}" ]; then
	salt=$(ynh_string_random --length=40)
	ynh_app_setting_set --key=salt --value=$salt
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="config.ini"
fi

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

mkdir -p "/var/log/$app/"
touch "/var/log/$app/$app.log"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "/var/log/$app/"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Personal finance manager" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL WOOB WITH PIP
#=================================================
ynh_script_progression "Installing woob..."

locale-gen C.UTF-8
update-locale C.UTF-8
ynh_safe_rm "${install_dir}/venv"
ynh_exec_as_app virtualenv --python=python3 --system-site-packages "${install_dir}/venv"
(
	set +o nounset
	source "${install_dir}/venv/bin/activate"
	set -o nounset

	ynh_hide_warnings ynh_exec_as_app RUSTUP_HOME="$install_dir"/.rustup CARGO_HOME="$install_dir"/.cargo bash -c 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y --default-toolchain=stable --profile=minimal'
	export PATH="$install_dir/.cargo/bin:$PATH"
	ynh_hide_warnings ynh_exec_as_app PATH=$PATH pip install --upgrade pip
	ynh_hide_warnings ynh_exec_as_app PATH=$PATH pip install --upgrade 'setuptools<71'
	ynh_hide_warnings ynh_exec_as_app PATH=$PATH pip install woob simplejson BeautifulSoup4 PyExecJS typing-extensions pdfminer.six Pillow chompjs --ignore-installed
	ynh_safe_rm "$install_dir/.cargo"
	ynh_safe_rm "$install_dir/.rustup"
	ynh_safe_rm "$install_dir/.cache"
	ynh_safe_rm "$install_dir/.local"
)

#=================================================
# INSTALL KRESUS WITH NPM
#=================================================
ynh_script_progression "Installing app..."

pushd $install_dir

	# In case of nodejs upgrade, remove the current node_modules to make sure there are no errors
	# linked to modules compiled for the previous version.
	ynh_safe_rm "$install_dir/node_modules"

	ynh_hide_warnings ynh_exec_as_app node_load_PATH yarn config set network-timeout 300000
	ynh_hide_warnings ynh_exec_as_app node_load_PATH yarn install --production
	ynh_hide_warnings ynh_exec_as_app node_load_PATH yarn cache clean --all
	ynh_safe_rm "$install_dir/.cache"
	ynh_safe_rm "$install_dir/.yarn"
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.ini" --destination="$install_dir/config.ini"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config.ini"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/config.ini"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Server is ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
